/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TribunalIdRouteImport } from './routes/tribunal.$id'
import { Route as ApiTribunalStreamRouteImport } from './routes/api/tribunal/stream'
import { Route as ApiTribunalJuryRouteImport } from './routes/api/tribunal/jury'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TribunalIdRoute = TribunalIdRouteImport.update({
  id: '/tribunal/$id',
  path: '/tribunal/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTribunalStreamRoute = ApiTribunalStreamRouteImport.update({
  id: '/api/tribunal/stream',
  path: '/api/tribunal/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTribunalJuryRoute = ApiTribunalJuryRouteImport.update({
  id: '/api/tribunal/jury',
  path: '/api/tribunal/jury',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tribunal/$id': typeof TribunalIdRoute
  '/api/tribunal/jury': typeof ApiTribunalJuryRoute
  '/api/tribunal/stream': typeof ApiTribunalStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tribunal/$id': typeof TribunalIdRoute
  '/api/tribunal/jury': typeof ApiTribunalJuryRoute
  '/api/tribunal/stream': typeof ApiTribunalStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tribunal/$id': typeof TribunalIdRoute
  '/api/tribunal/jury': typeof ApiTribunalJuryRoute
  '/api/tribunal/stream': typeof ApiTribunalStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tribunal/$id'
    | '/api/tribunal/jury'
    | '/api/tribunal/stream'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tribunal/$id' | '/api/tribunal/jury' | '/api/tribunal/stream'
  id:
    | '__root__'
    | '/'
    | '/tribunal/$id'
    | '/api/tribunal/jury'
    | '/api/tribunal/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TribunalIdRoute: typeof TribunalIdRoute
  ApiTribunalJuryRoute: typeof ApiTribunalJuryRoute
  ApiTribunalStreamRoute: typeof ApiTribunalStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tribunal/$id': {
      id: '/tribunal/$id'
      path: '/tribunal/$id'
      fullPath: '/tribunal/$id'
      preLoaderRoute: typeof TribunalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tribunal/stream': {
      id: '/api/tribunal/stream'
      path: '/api/tribunal/stream'
      fullPath: '/api/tribunal/stream'
      preLoaderRoute: typeof ApiTribunalStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tribunal/jury': {
      id: '/api/tribunal/jury'
      path: '/api/tribunal/jury'
      fullPath: '/api/tribunal/jury'
      preLoaderRoute: typeof ApiTribunalJuryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TribunalIdRoute: TribunalIdRoute,
  ApiTribunalJuryRoute: ApiTribunalJuryRoute,
  ApiTribunalStreamRoute: ApiTribunalStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
